name: CI/CD for Node.js App on AKS (Fedora)

on:
  push:
    branches:
    - main # Run CI/CD when code is merged into the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env: # Declare environment variables once for the entire job
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (latest)
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install npm
      run: npm install
      working-directory: ./app

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Set up Terraform (latest)
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-config

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform-config

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform-config

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: 'latest'

    - name: Deploy using Helm
      run: |
        helm upgrade --install myapp ./helm-config
        kubectl get pods --namespace default

    - name: Verify Application
      run: |
        kubectl get services
        kubectl get pods
