name: CI/CD for Node.js App on AKS
on:
  push:
    branches:
    - main # Run CI/CD when code is merged into the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env: # Declare environment variables once for the entire job
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install npm
      run: npm install
      working-directory: ./app

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-config

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform-config

    - name: Terraform Apply
      id: cubeconfig_capture
      run: |
        terraform apply -auto-approve
      working-directory: ./terraform-config

    # - name: Azure Login
    #   uses: azure/login@v2
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy using Helm
    uses: WyriHaximus/github-action-helm3@v4.0.1
    with:
      exec: helm upgrade --install ${{ github.event.repository.name }} ./helm-config --kubeconfig $GITHUB_WORKSPACE/terraform-config/kubeconfig

    - name: Verify Application
      run: |
        kubectl get services
        kubectl get pods
